modLoader = "javafml"
loaderVersion = "[21,)"

license = "LGPL-3.0"

[[mods]]
modId = "eat_egg"
version = "${version}"
displayName = "Eat Egg"
logoFile = "assets/eat_egg/icon.png"
credits = "Original by chameleonwren"
authors = "MomoNyako, chameleonwren"
description = "Eat Eggs 的非官方移植版"

[[dependencies.eat_egg]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eat_egg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"
